apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-logstash-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-logstash-pusher
  template:
    metadata:
      labels:
        app: go-logstash-pusher
    spec:
      hostNetwork: true
      containers:
      - name: go-logstash-pusher
        image: utilities/go-logstash-pusher:v0.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
